# This is a workflow to test your PowerShell module with TestingHelper
# https://github.com/rulasg/DemoPsModule/blob/main/.github/workflows/test_with_TestingHelper.yml

name: Test TestingHelper Setup Action

# Controls when the workflow will run
on:

  # Push and push-pr events trigger the workflow
  push:
      branches: [ main ]
  pull_request:

  # Allow to be called from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # To run test we only need to read the repository
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-without-Version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Run test with TestingHelper using local branch version
      - name: Run local action
        uses: ./

      - name: Assert the test run
        shell: pwsh
        run: |
          $module = Get-Module -Name Testinghelper -ListAvailable
  
          # Check if module is null
          if ($null -eq $module) {
              # Import module
              throw "Module not found"
          } else {
              $module
              write-host "TestingHelper module found !!" -ForegroundColor Green
          }

  test-with-Version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Run test with TestingHelper using local branch version
      - name: Run local action
        uses: ./
        with:
          Version: '1.3'

      - name: Assert the test run
        shell: pwsh
        run: |
          $module = Get-Module -Name Testinghelper -ListAvailable
  
          # Check if module is null
          if ('1.3' -ne $module.version.ToString()) {
              # Import module
              throw "Module not found"
          } else {
              $module
              write-host "TestingHelper module found !!" -ForegroundColor Green
          }

  test-with-AllowPrerelease-false:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Run test with TestingHelper using local branch version
      - name: Run local action
        uses: ./
        with:
          AllowPreReleaseVersions: 'false'

      - name: Assert the test run
        shell: pwsh
        run: |
          $module = Get-Module -Name Testinghelper -ListAvailable
  
          # Check if module is null
          if ('2.0' -ne $module.version.ToString()) {
              # Import module
              throw "Module not found"
          } else {
              $module
              write-host "TestingHelper module found !!" -ForegroundColor Green
          }

